- name: Configure DC01 - Install ADDS and DNS
  hosts: dc
  gather_facts: no
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Install DNS feature
      win_feature:
        name: DNS
        state: present
        include_management_tools: yes
