name: Azure Login Test

on:
  workflow_dispatch:

jobs:
  test-azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current subscription
        run: az account show
