name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan (with auto-unlock)
        run: |
          set +e
          terraform -chdir=terraform plan -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}"
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            LOCK_ID=$(terraform -chdir=terraform plan -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}" 2>&1 | grep -A3 "Error acquiring the state lock" | grep "ID:" | awk '{print $2}')
            if [ -n "$LOCK_ID" ]; then
              echo "Found lock ID: $LOCK_ID — unlocking..."
              terraform -chdir=terraform force-unlock -force $LOCK_ID || true
              echo "Retrying terraform plan..."
              terraform -chdir=terraform plan -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}"
            else
              echo "No lock ID detected, failing..."
              exit $EXIT_CODE
            fi
          fi
          set -e

      - name: Terraform Apply (with auto-unlock)
        if: github.ref == 'refs/heads/main'
        run: |
          set +e
          terraform -chdir=terraform apply -auto-approve -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}"
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            LOCK_ID=$(terraform -chdir=terraform apply -auto-approve -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}" 2>&1 | grep -A3 "Error acquiring the state lock" | grep "ID:" | awk '{print $2}')
            if [ -n "$LOCK_ID" ]; then
              echo "Found lock ID: $LOCK_ID — unlocking..."
              terraform -chdir=terraform force-unlock -force $LOCK_ID || true
              echo "Retrying terraform apply..."
              terraform -chdir=terraform apply -auto-approve -var="vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }}"
            else
              echo "No lock ID detected, failing..."
              exit $EXIT_CODE
            fi
          fi
          set -e
